CREATE TABLE IF NOT EXISTS gerne (
	id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS artist (
	id SERIAL PRIMARY KEY,
	FIO VARCHAR(60) NOT NULL,
	second_name VARCHAR(60),
	id_gerne INTEGER REFERENCES gerne(id)
);


CREATE TABLE IF NOT EXISTS album (
	id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
	age DATE NOT NULL,
	id_artist INTEGER REFERENCES artist(id)
);

CREATE TABLE IF NOT EXISTS tracks (
	id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
	duration TIME NOT NULL,
	id_album INTEGER REFERENCES album(id)
);